SELECT VFAM,
       PNAME
FROM VYKLAD v INNER JOIN PREDMET p on v.VNOM = p.VNOM

SELECT v.VFAM,
       p.PNAME,
       p.GOD
FROM VYKLAD v INNER JOIN PREDMET p
    ON v.VNOM = p.VNOM
    AND p.GOD > 100

SELECT s.SFAM,
       u.PNOM
FROM STUDENTS s LEFT JOIN USPISH u
    ON s.SNOM = u.SNOM

SELECT s.SFAM,
       u.PNOM
FROM USPISH u RIGHT JOIN STUDENTS s
    ON s.SNOM = u.SNOM

SELECT s.SIMA,
       p.PNAME
FROM STUDENTS s CROSS JOIN PREDMET p

SELECT s.SFAM,
       p.PNAME
FROM STUDENTS s CROSS JOIN USPISH u
    ON s.SNOM = u.SNOM
    CROSS JOIN PREDMET p
        ON u.PNOM = p.PNOM

SELECT * FROM PREDMET
    WHERE VNOM IN
          (SELECT VNOM FROM VYKLAD WHERE VIMA = 'Бачишина')

SELECT SFAM FROM STUDENTS
    WHERE STIP IN
          (SELECT MAX(STIP) FROM STUDENTS)

SELECT * FROM STUDENTS
    WHERE SNOM = ALL (SELECT SNOM FROM USPISH WHERE OCINKA < 3)

SELECT SFAM
FROM STUDENTS
    WHERE SNOM = ANY (SELECT SNOM FROM USPISH WHERE OCINKA = 2)

SELECT *
FROM STUDENTS
    WHERE SNOM = ALL (SELECT SNOM FROM USPISH WHERE OCINKA > 2)

SELECT VFAM
FROM VYKLAD
    WHERE VNOM = ANY
        (SELECT VNOM FROM USPISH WHERE OCINKA > 2 HAVING COUNT(*) > 1)

SELECT SFAM
FROM STUDENTS
    WHERE SNOM = ANY (SELECT SNOM FROM USPISH WHERE DATA = '01.02.2020')

6)-

SELECT SFAM
FROM STUDENTS
    WHERE SNOM = ANY(SELECT SNOM FROM STUDENTS WHERE SIMA = 'someName')

SELECT DISTINCT SFAM
FROM STUDENTS
    WHERE SNOM = ANY (SELECT SNOM FROM USPISH)
