SELECT SFAM, SIMA, STIP FROM STUDENTS ORDER BY SFAM
SELECT STIP*2 as NSTIP FROM STUDENTS
SELECT SFAM, SIMA FROM STUDENTS WHERE STIP=75
SELECT SNOM FROM USPISH WHERE OCINKA>3
SELECT * FROM USPISH WHERE OCINKA IN (4,5)
SELECT SFAM FROM STUDENTS WHERE SIMA IN('Дмитро', 'Михайло')
SELECT SNOM FROM USPISH WHERE DATA BETWEEN '1.06.2005' AND '15.06.2005'
SELECT SNOM FROM USPISH WHERE DATA LIKE '%.06.%'
SELECT SNOM FROM STUDENTS WHERE FOTO IS NULL
SELECT DISTINCT SNOM FROM USPISH WHERE OCINKA BETWEEN 0 AND 2
SELECT * FROM VYKLAD WHERE VFAM LIKE 'Б%'
SELECT * FROM PREDMET WHERE PNAME LIKE '%бази%'
SELECT COUNT(*) FROM STUDENTS
SELECT SUM(STIP) FROM STUDENTS WHERE GRUP='ПМ-31'
SELECT COUNT(*) FROM STUDENTS WHERE STIP>0
SELECT AVG(OCINKA) FROM USPISH
SELECT MAX(OCINKA) as MAXOCINKA, MIN(OCINKA) as MINOCINKA FROM USPISH
SELECT MIN(OCINKA) as MINOCINKA FROM USPISH WHERE OCINKA>2
SELECT COUNT(*) FROM USPISH
SELECT COUNT(*) FROM USPISH WHERE OCINKA>2
SELECT AVG(OCINKA) FROM USPISH
SELECT COUNT(*) FROM STUDENTS WHERE FORM IN('бюджет','платна')
