CREATE PROCEDURE MinStip()
    SELECT MIN(STIP) AS Min_Stip FROM STUDENTS;

CREATE PROCEDURE MaxStip()
    SELECT SFAM FROM STUDENTS WHERE STIP IN
                                    (SELECT MAX(STIP) FROM STUDENTS);

CREATE PROCEDURE IndexStip(IN coef double)
    UPDATE STUDENTS SET STIP=STIP*coef;

CREATE PROCEDURE ShowStudByStip(IN stip double)
    SELECT SFAM FROM STUDENTS WHERE STIP = stip;

CREATE PROCEDURE CalcGodSum()
    SELECT SUM(GOD)
    FROM PREDMET


